//
// Created by Casper Skjærris on 2019-03-07.
//

#ifndef INVENTORYMANAGEMENTSIMULATOR_CUSTOMER_H
#define INVENTORYMANAGEMENTSIMULATOR_CUSTOMER_H
struct Customer{

};

#endif //INVENTORYMANAGEMENTSIMULATOR_CUSTOMER_H
