//
// Created by Casper Skjærris on 2019-03-07.
//

#ifndef INVENTORYMANAGEMENTSIMULATOR_VENDOR_H
#define INVENTORYMANAGEMENTSIMULATOR_VENDOR_H
struct Vendor{

};

#endif //INVENTORYMANAGEMENTSIMULATOR_VENDOR_H
